### ISSUE TITLE
FastCGI applications

### ISSUE THREAD

**Issue by ofek** [fastai/fastcgi#29]
@jph00 Hello there!

We're trying to remove our dependency on [flup](https://www.saddi.com/software/flup/)/[flup-py3](https://pypi.org/project/flup-py3/) for our [PHP-FPM](https://docs.datadoghq.com/integrations/php_fpm/) integration. Luckily, I stumbled upon this library and now am reading the docs but I don't quite understand the difference in the client/server model between these libraries.

All the logic we require is essentially captured in [this function](https://github.com/DataDog/integrations-core/blob/7.33.x/php_fpm/datadog_checks/php_fpm/php_fpm.py#L177-L219). Is that something that is currently supported?

Thanks 🙂

**Comment by coignetp** [comment]
Hello @jph00! Looking at the code and the examples, it seems this library is mostly intended to create FCGI endpoints. I can't find out if it's possible to use it as a client, and query endpoints. Could this library be used to reach a specific endpoint using FCGI?
Thanks!

**Comment by jph00** [comment]
@coignetp I don't think I ever really tried that - I just used `http2cgi` for client testing.
